// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using VentaProducto_API.Datos;

#nullable disable

namespace VentaProductoAPI.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    partial class ApplicationDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("VentaProducto_API.Modelos.Producto", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("Cantidad")
                        .HasColumnType("int");

                    b.Property<string>("Detalle")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("FechaAcualizacion")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("FechaCreacion")
                        .HasColumnType("datetime2");

                    b.Property<string>("ImageUrl")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Precio")
                        .HasColumnType("int");

                    b.Property<string>("Tamaño")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Productos");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Cantidad = 0,
                            Detalle = "C",
                            FechaAcualizacion = new DateTime(2024, 4, 2, 16, 43, 52, 862, DateTimeKind.Local).AddTicks(2631),
                            FechaCreacion = new DateTime(2024, 4, 2, 16, 43, 52, 862, DateTimeKind.Local).AddTicks(2618),
                            ImageUrl = "",
                            Nombre = "Colibri",
                            Precio = 3000,
                            Tamaño = "Mediano"
                        },
                        new
                        {
                            Id = 2,
                            Cantidad = 0,
                            Detalle = "C",
                            FechaAcualizacion = new DateTime(2024, 4, 2, 16, 43, 52, 862, DateTimeKind.Local).AddTicks(2633),
                            FechaCreacion = new DateTime(2024, 4, 2, 16, 43, 52, 862, DateTimeKind.Local).AddTicks(2633),
                            ImageUrl = "",
                            Nombre = "Corazon",
                            Precio = 2000,
                            Tamaño = "Mediano"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
